### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by beydogan** [kevinoid/swagger-spec-validator#38]
I was getting `Error: certificate has expired` error then I realised `https://online.swagger.io/validator/debug` has an expired certificate. They renewed their certificate but now they are using GoDaddy, not DigiCert. So I guess `certs` should be updated with these https://certs.godaddy.com/repository ?

**Comment by kevinoid** [comment]
Thanks @beydogan!  Right you are.  Looks like swagger-api/validator-badge#98 affects their new GoDaddy certificate as well.

I just pushed some commits to replace the DigiCert intermediate certificates with the necessary GoDaddy ones.  I'll publish a new version with these updates shortly.

**Comment by kevinoid** [comment]
I just published [v2.0.0](https://github.com/kevinoid/swagger-spec-validator/releases/tag/v2.0.0) which includes the fix.  If that doesn't solve the issue for you, please reopen.

Thanks again for reporting it!

**Comment by beydogan** [comment]
Thank you @kevinoid looks like its fixed.
